INFO:	23:40:35,945 werkzeug INFO  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
INFO:	23:40:52,654 werkzeug INFO 127.0.0.1 - - [19/Nov/2020 23:40:52] "[31m[1mGET / HTTP/1.1[0m" 405 -
ERROR:	23:46:38,8 app ERROR Exception on / [POST]
Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 7, in post
    token = request.headers['Authorization']
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_AUTHORIZATION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 15, in post
    return format_reponse(6, 'Internal Server Error', None, 'Internal Server Error'), status.HTTP_500_INTERNAL_SERVER_ERROR
UnboundLocalError: local variable 'status' referenced before assignment
INFO:	23:46:38,297 werkzeug INFO 127.0.0.1 - - [19/Nov/2020 23:46:38] "[35m[1mPOST / HTTP/1.1[0m" 500 -
ERROR:	23:47:55,443 app ERROR Exception on / [POST]
Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 7, in post
    token = request.headers['Authorization']
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_AUTHORIZATION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 15, in post
    return format_reponse(6, 'Internal Server Error', None, 'Internal Server Error'), status.HTTP_500_INTERNAL_SERVER_ERROR
UnboundLocalError: local variable 'status' referenced before assignment
INFO:	23:47:55,446 werkzeug INFO 127.0.0.1 - - [19/Nov/2020 23:47:55] "[35m[1mPOST / HTTP/1.1[0m" 500 -
ERROR:	23:49:26,364 app ERROR Exception on / [POST]
Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 10, in post
    return format_reponse(status.HTTP_200_OK, 'REQUEST_SUCCESS', None, None)
AttributeError: 'bool' object has no attribute 'HTTP_200_OK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 15, in post
    return format_reponse(6, 'Internal Server Error', None, 'Internal Server Error'), status.HTTP_500_INTERNAL_SERVER_ERROR
AttributeError: 'bool' object has no attribute 'HTTP_500_INTERNAL_SERVER_ERROR'
INFO:	23:49:26,367 werkzeug INFO 127.0.0.1 - - [19/Nov/2020 23:49:26] "[35m[1mPOST / HTTP/1.1[0m" 500 -
ERROR:	23:55:28,78 app ERROR Exception on / [POST]
Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 10, in post
    return format_reponse(status.HTTP_200_OK, 'REQUEST_SUCCESS', None, None)
AttributeError: 'bool' object has no attribute 'HTTP_200_OK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/venv-write-down/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/media/nghialuffy/CODE/Chuyen Nganh IT/Nam_4/write_down_project/backend/Controller/homepage.py", line 15, in post
    return format_reponse(6, 'Internal Server Error', None, 'Internal Server Error'), status.HTTP_500_INTERNAL_SERVER_ERROR
AttributeError: 'bool' object has no attribute 'HTTP_500_INTERNAL_SERVER_ERROR'
INFO:	23:55:28,80 werkzeug INFO 127.0.0.1 - - [19/Nov/2020 23:55:28] "[35m[1mPOST / HTTP/1.1[0m" 500 -
